#include "alosmm/engine.hpp"
#include <csignal>
namespace alosmm {
static std::atomic<bool>* g_stop=nullptr;static void sig_handler(int){if(g_stop)g_stop->store(true);}
Engine::Engine(Config c):cfg_(std::move(c)),models_(cfg_),policy_(cfg_,models_),surface_(0.06),costs_(cfg_),stats_(cfg_){std::filesystem::create_directories(cfg_.state_dir);std::filesystem::create_directories(cfg_.stats_dir);}
void Engine::on_book(const Book& b){if(!market_q_.push(b))++dropped_;}
static double zscore(const RunningMoments&r,double x){return r.n()>30?(x-r.mean())/std::max(1e-6,r.stdev()):0.0;}
void Engine::update_signals(const Book&b,const std::optional<Book>&old){if(b.token!=cfg_.futures_token)return;if(old&&old->valid()&&b.valid()){double e=0;for(int l=0;l<std::min({5,old->bid_count,b.bid_count});++l){auto&n=b.bids[l];auto&o=old->bids[l];e+=(n.price>=o.price?n.qty:0)-(n.price<=o.price?o.qty:0);}for(int l=0;l<std::min({5,old->ask_count,b.ask_count});++l){auto&n=b.asks[l];auto&o=old->asks[l];e-=(n.price<=o.price?n.qty:0)-(n.price>=o.price?o.qty:0);}ofi_accum_+=e;vol_accum_+=std::max<int64_t>(0,b.volume-old->volume);}last_future_=b;}
void Engine::process_books(){Book b;while(market_q_.pop(b)){++feed_msgs_;const int64_t process_ns=now_unix_ns();if(process_ns>=b.recv_ts_ns)max_queue_delay_us_=std::max(max_queue_delay_us_,static_cast<double>(process_ns-b.recv_ts_ns)/1e3);auto it=books_.find(b.token);std::optional<Book>old;if(it!=books_.end())old=it->second;update_signals(b,old);books_[b.token]=b;double lag=(b.exchange_ts_ns>0?static_cast<double>(b.recv_ts_ns-b.exchange_ts_ns)/1e6:0);if(lag>0&&lag<60'000)max_feed_lag_ms_=std::max(max_feed_lag_ms_,lag);for(auto&p:pending_)if(p.active&&p.inst.token==b.token){if(b.ask()>0)p.min_ask=std::min(p.min_ask,b.ask());if(b.bid()>0)p.max_bid=std::max(p.max_bid,b.bid());const bool new_trade=old.has_value()&&b.volume>old->volume;if(new_trade&&b.ltp>0){p.min_ltp=std::min(p.min_ltp,b.ltp);p.max_ltp=std::max(p.max_ltp,b.ltp);}}}}

void Engine::process_order_updates(){
    OrderUpdate u;
    while(order_q_.pop(u)){
        if(router_)router_->on_order_update(u);
        auto& prev=live_fill_state_[u.order_id];
        if(u.filled_qty<=prev.filled_qty)continue;
        const int delta_qty=u.filled_qty-prev.filled_qty;
        double incremental_price=u.avg_price;
        if(prev.filled_qty>0&&u.avg_price>0&&prev.avg_price>0){
            incremental_price=(u.avg_price*u.filled_qty-prev.avg_price*prev.filled_qty)/static_cast<double>(delta_qty);
        }
        const Instrument* inst=nullptr;
        if(u.token){for(const auto& x:cfg_.instruments)if(x.token==u.token){inst=&x;break;}}
        if(!inst&&!u.symbol.empty()){for(const auto& x:cfg_.instruments)if(x.trading_symbol==u.symbol){inst=&x;break;}}
        if(!inst){std::cerr<<"LIVE SAFETY STOP: fill for unknown instrument order="<<u.order_id<<" symbol="<<u.symbol<<" token="<<u.token<<"\n";stop_.store(true);return;}
        try{
            policy_.on_fill(*inst,u.side,incremental_price,delta_qty);
            if(!policy_.inventory().empty())pinned_strike_=inst->strike;else pinned_strike_.reset();
            FillEvent fe{inst->cp,u.side,inst->token,inst->strike,inst->trading_symbol,incremental_price,delta_qty,u.order_id,u.recv_ts_ns};
            stats_.fill(fe,policy_.inventory(),false);
            prev.filled_qty=u.filled_qty;prev.avg_price=u.avg_price;
        }catch(const std::exception&e){
            std::cerr<<"LIVE SAFETY STOP: inventory reconciliation failed: "<<e.what()<<"\n";
            stop_.store(true);return;
        }
    }
}

double Engine::dw5(const Book&b)const{double num=0,den=0;for(int i=0;i<5;++i){double w=1.0/(i+1.0),qb=i<b.bid_count?static_cast<double>(b.bids[i].qty):0,qa=i<b.ask_count?static_cast<double>(b.asks[i].qty):0;num+=w*(qb-qa);den+=w*(qb+qa);}return den>0?num/den:0;}
double Engine::micro_shift(const Book&b)const{if(!b.valid()||b.bid_count<1||b.ask_count<1)return 0;double qb=b.bids[0].qty,qa=b.asks[0].qty;if(qb+qa<=0)return 0;double micro=(b.ask()*qb+b.bid()*qa)/(qb+qa);return micro-b.mid();}
std::optional<std::pair<Instrument,Instrument>> Engine::select_atm(double ref)const{if(ref<=0)return std::nullopt;std::map<double,std::array<std::optional<Instrument>,2>>m;int64_t front=std::numeric_limits<int64_t>::max();for(auto&i:cfg_.instruments)if(i.expiry_unix_ns>now_unix_ns())front=std::min(front,i.expiry_unix_ns);for(auto&i:cfg_.instruments)if(i.expiry_unix_ns==front)m[i.strike][static_cast<size_t>(i.cp)]=i;if(pinned_strike_&& !policy_.inventory().empty()){auto it=m.find(*pinned_strike_);if(it!=m.end()&&it->second[0]&&it->second[1])return std::make_pair(*it->second[0],*it->second[1]);return std::nullopt;}double best=1e100;std::optional<std::pair<Instrument,Instrument>>out;for(auto&[K,a]:m)if(a[0]&&a[1]){double d=std::abs(K-ref);if(d<best){best=d;out=std::make_pair(*a[0],*a[1]);}}return out;}
FeatureState Engine::build_state(const Instrument&i,const Book&b,const SurfaceFit&f,const std::array<Greeks,2>&gs,int64_t now){FeatureState s;s.ts_ns=now;s.cp=i.cp;s.best_bid=b.bid();s.best_ask=b.ask();s.mid=b.mid();s.spread=b.spread();s.fair_value=surface_.fair_option_price(i,f,now);s.surface_residual=s.fair_value-s.mid;s.dw5_imbalance=dw5(b);s.micro_shift=micro_shift(b);s.quote_age_s=ns_to_seconds(now-b.recv_ts_ns);s.surface_age_s=ns_to_seconds(now-f.fitted_at_ns);s.surface_rmse=f.rmse_iv;s.pair_dispersion=f.pair_dispersion;s.surface_pairs=f.pairs;s.surface_forward=f.forward;s.surface_theta=f.theta;s.surface_rho=f.rho;s.surface_phi=f.phi;s.greeks=surface_.greeks(i,f,now);s.tte_days=std::max(0.0,ns_to_seconds(i.expiry_unix_ns-now)/(24*3600));if(last_future_){s.future_age_s=ns_to_seconds(now-last_future_->recv_ts_ns);s.futures_ofi_z=zscore(ofi_hist_,ofi_accum_);s.trade_intensity_z=zscore(vol_hist_,vol_accum_);double rawgap=last_future_->mid()-f.forward;double adj=rawgap-basis_.value(rawgap);s.synthetic_gap_z=zscore(gap_hist_,adj);}s.inventory_lots=policy_.inventory().get(i).lots;s.portfolio_delta=policy_.inventory().delta(gs);s.portfolio_vega=policy_.inventory().vega(gs);s.portfolio_gamma=policy_.inventory().gamma(gs);return s;}
bool Engine::cf_fill(const Pending&p,Side s,double q)const{return s==Side::Buy?(p.min_ask<=q||p.min_ltp<=q):(p.max_bid>=q||p.max_ltp>=q);}
void Engine::mature(Pending&p,int64_t now){if(!p.active||now<p.maturity_ns)return;auto oit=books_.find(p.inst.token);auto fit=books_.find(cfg_.futures_token);if(oit==books_.end()||fit==books_.end()||!oit->second.valid()||!fit->second.valid()){p.active=false;return;}double om=oit->second.mid(),fm=fit->second.mid();for(auto&c:p.candidates){bool fill=cf_fill(p,c.side,c.price);double cond=0;if(fill){if(c.side==Side::Buy)cond=om-c.price-p.delta*(fm-p.fut_entry)-costs_.buy_points(c.price,p.inst.lot_size);else cond=c.price-om+p.delta*(fm-p.fut_entry)-costs_.sell_points(c.price,p.inst.lot_size);}double ev=fill?cond:0;models_.update(p.inst.cp,c.side,c.offset,p.state,fill,cond,ev);CounterfactualLabel l{p.start_ns,now,p.inst.cp,c.side,c.offset,c.price,c.pred.pfill,c.pred.conditional,c.pred.calibrated_ev,fill,cond,ev};stats_.counterfactual(l,p.state,p.inst);}
    if(cfg_.mode==Mode::Shadow){auto apply=[&](const QuoteAction&a){if(!a.enabled||!cf_fill(p,a.side,a.price))return;try{int qty=p.inst.lot_size*cfg_.quantity_lots;policy_.on_fill(p.inst,a.side,a.price,qty);if(!policy_.inventory().empty())pinned_strike_=p.inst.strike;else pinned_strike_.reset();FillEvent fe{p.inst.cp,a.side,p.inst.token,p.inst.strike,p.inst.trading_symbol,a.price,qty,"SHADOW",now};stats_.fill(fe,policy_.inventory(),true);}catch(const std::exception&e){std::cerr<<"shadow fill blocked: "<<e.what()<<"\n";}};apply(p.selected.ask);apply(p.selected.bid);}p.active=false;}
void Engine::submit_live(const Instrument&i,const ContractDecision&d){if(cfg_.mode!=Mode::Live||!router_)return;auto submit=[&](const QuoteAction&a){OrderIntent o;o.cp=i.cp;o.side=a.side;o.symbol=i.trading_symbol;o.token=i.token;o.quantity=i.lot_size*cfg_.quantity_lots;o.ts_ns=d.bid.ts_ns;o.kind=a.enabled?OrderIntent::Kind::Place:OrderIntent::Kind::Cancel;o.price=a.enabled?a.price:0;router_->submit_desired(o);};submit(d.bid);submit(d.ask);}
void Engine::decision_cycle(int64_t now){const auto cycle_start=Clock::now();for(auto&p:pending_)mature(p,now);auto fitf=books_.find(cfg_.futures_token);if(fitf==books_.end()||!fitf->second.valid())return;double ref=fitf->second.mid();auto atm=select_atm(ref);if(!atm)return;double K=atm->first.strike;++surface_tries_;const auto surface_start=Clock::now();auto sf=surface_.fit_leave_strike_out(cfg_.instruments,books_,K,now);max_surface_fit_us_=std::max(max_surface_fit_us_,std::chrono::duration<double,std::micro>(Clock::now()-surface_start).count());if(sf.valid)++surface_ok_;if(!sf.valid&&cfg_.require_surface)return;double rawgap=fitf->second.mid()-sf.forward;basis_.update(rawgap);gap_hist_.add(rawgap-basis_.value(rawgap));ofi_hist_.add(ofi_accum_);vol_hist_.add(vol_accum_);
    std::array<Greeks,2>gs{surface_.greeks(atm->first,sf,now),surface_.greeks(atm->second,sf,now)};for(auto&inst:{atm->first,atm->second}){auto bit=books_.find(inst.token);if(bit==books_.end()||!bit->second.valid())continue;FeatureState s=build_state(inst,bit->second,sf,gs,now);auto d=policy_.decide(s,inst,gs);++decisions_;stats_.decision(s,d,policy_.inventory(),inst);if(policy_.should_replace(inst,d))submit_live(inst,d);Pending p;p.active=true;p.start_ns=now;p.maturity_ns=now+static_cast<int64_t>(cfg_.counterfactual_horizon_ms)*1'000'000LL;p.state=s;p.inst=inst;p.selected=d;p.fut_entry=fitf->second.mid();p.delta=s.greeks.delta;p.min_ask=bit->second.ask();p.max_bid=bit->second.bid();p.min_ltp=1e100;p.max_ltp=-1e100;double reservation=d.reservation_value;for(Side side:{Side::Buy,Side::Sell})for(double off:cfg_.offsets){auto pred=models_.predict(inst.cp,side,off,s);double q=side==Side::Buy?std::min(s.best_bid,floor_tick(reservation-off,inst.tick_size)):std::max(s.best_ask,ceil_tick(reservation+off,inst.tick_size));p.candidates.push_back({side,off,q,pred});}pending_[static_cast<size_t>(inst.cp)]=std::move(p);}ofi_accum_=0;vol_accum_=0;max_decision_cycle_us_=std::max(max_decision_cycle_us_,std::chrono::duration<double,std::micro>(Clock::now()-cycle_start).count());}
int Engine::run(){std::cout<<config_summary(cfg_)<<"\n";LiveGate::require(cfg_);if(cfg_.futures_token==0)throw std::runtime_error("configuration invalid: set the current NIFTY futures token before running");if(cfg_.instruments.size()<static_cast<size_t>(2*(cfg_.min_surface_pairs+1)))throw std::runtime_error("configuration invalid: load at least min_surface_pairs+1 paired option strikes");for(const auto&i:cfg_.instruments)if(i.token==0||i.trading_symbol.empty())throw std::runtime_error("configuration invalid: option token/symbol missing");models_.load(std::filesystem::path(cfg_.state_dir)/"model_state.dat");stats_.start();KotakRestClient rest(cfg_);KotakSession session;try{session=rest.login();std::cout<<"Kotak session established; dataCenter="<<session.data_center<<"\n";}catch(const std::exception&e){stats_.stop();throw;}std::vector<uint32_t>tokens;tokens.reserve(cfg_.instruments.size()+1);for(auto&i:cfg_.instruments)tokens.push_back(i.token);if(cfg_.futures_token)tokens.push_back(cfg_.futures_token);std::sort(tokens.begin(),tokens.end());tokens.erase(std::unique(tokens.begin(),tokens.end()),tokens.end());feed_=std::make_unique<SFeedClient>(cfg_,session,tokens,[this](const Book&b){on_book(b);});router_=std::make_unique<OrderRouter>(cfg_,session);router_->start();if(cfg_.mode==Mode::Live){order_updates_=std::make_unique<OrderUpdateClient>(session,[this](const OrderUpdate&u){if(!order_q_.push(u)){std::cerr<<"LIVE SAFETY STOP: order-update queue overflow\n";stop_.store(true);}});}g_stop=&stop_;std::signal(SIGINT,sig_handler);std::signal(SIGTERM,sig_handler);feed_thread_=std::thread([this]{feed_->run(stop_);});if(order_updates_)order_update_thread_=std::thread([this]{order_updates_->run(stop_);});last_decision_ns_=now_unix_ns();last_health_ns_=last_decision_ns_;
    while(!stop_){process_books();process_order_updates();int64_t now=now_unix_ns();if(now-last_decision_ns_>=static_cast<int64_t>(cfg_.decision_interval_ms)*1'000'000LL){decision_cycle(now);last_decision_ns_=now;}if(now-last_health_ns_>=static_cast<int64_t>(cfg_.health_interval_s)*1'000'000'000LL){double sr=surface_tries_?static_cast<double>(surface_ok_)/surface_tries_:0;stats_.health(now,feed_msgs_,decisions_,dropped_,max_feed_lag_ms_,max_queue_delay_us_,max_surface_fit_us_,max_decision_cycle_us_,sr);last_health_ns_=now;max_feed_lag_ms_=0;max_queue_delay_us_=0;max_surface_fit_us_=0;max_decision_cycle_us_=0;}std::this_thread::sleep_for(Ms(1));}
    if(feed_thread_.joinable())feed_thread_.join();if(order_update_thread_.joinable())order_update_thread_.join();router_->stop();
    const auto persistent_state=std::filesystem::path(cfg_.state_dir)/"model_state.dat";
    models_.save(persistent_state);
    const auto daily_state_dir=std::filesystem::path(cfg_.stats_dir)/utc_date();
    std::filesystem::create_directories(daily_state_dir);
    models_.save(daily_state_dir/"model_state_eod.dat");
    stats_.write_day_summary(models_,policy_.inventory());stats_.stop();return 0;}
int Engine::self_test(){std::cout<<"Self-test: long-only and policy cold start\n";Instrument c{1,"nse_fo","TESTCE",CP::Call,100,now_unix_ns()+24LL*3600*1'000'000'000,65,.05};try{policy_.on_fill(c,Side::Sell,5,65);std::cerr<<"FAILED: negative sell allowed\n";return 2;}catch(const std::exception&){ }policy_.on_fill(c,Side::Buy,5,65);policy_.on_fill(c,Side::Sell,5.5,65);if(policy_.inventory().get(c).lots!=0)return 3;std::string t=KotakRestClient::generate_totp("JBSWY3DPEHPK3PXP",59);if(t.empty())return 4;std::cout<<"Self-test PASS\n";return 0;}
} // namespace alosmm
