#include "alosmm/kotak_rest.hpp"
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>
#include <openssl/hmac.h>
#include <cctype>
namespace alosmm {
namespace pt=boost::property_tree;
static size_t wr(char*p,size_t s,size_t n,void*u){auto*out=static_cast<std::string*>(u);out->append(p,s*n);return s*n;}
HttpClient::HttpClient(){curl_global_init(CURL_GLOBAL_DEFAULT);curl_=curl_easy_init();if(!curl_)throw std::runtime_error("curl init failed");curl_easy_setopt(curl_,CURLOPT_HTTP_VERSION,CURL_HTTP_VERSION_2TLS);curl_easy_setopt(curl_,CURLOPT_TCP_KEEPALIVE,1L);curl_easy_setopt(curl_,CURLOPT_TCP_NODELAY,1L);curl_easy_setopt(curl_,CURLOPT_TCP_KEEPIDLE,20L);curl_easy_setopt(curl_,CURLOPT_TCP_KEEPINTVL,10L);curl_easy_setopt(curl_,CURLOPT_CONNECTTIMEOUT_MS,3000L);curl_easy_setopt(curl_,CURLOPT_TIMEOUT_MS,5000L);curl_easy_setopt(curl_,CURLOPT_NOSIGNAL,1L);}
HttpClient::~HttpClient(){if(curl_)curl_easy_cleanup(curl_);curl_global_cleanup();}
HttpClient::Response HttpClient::post(const std::string&url,const std::vector<std::string>&h,const std::string&body,const std::string&ct){struct curl_slist*hs=nullptr;for(auto&s:h)hs=curl_slist_append(hs,s.c_str());std::string cth="Content-Type: "+ct;hs=curl_slist_append(hs,cth.c_str());Response r;curl_easy_reset(curl_);curl_easy_setopt(curl_,CURLOPT_URL,url.c_str());curl_easy_setopt(curl_,CURLOPT_HTTPHEADER,hs);curl_easy_setopt(curl_,CURLOPT_POST,1L);curl_easy_setopt(curl_,CURLOPT_POSTFIELDS,body.c_str());curl_easy_setopt(curl_,CURLOPT_POSTFIELDSIZE,static_cast<long>(body.size()));curl_easy_setopt(curl_,CURLOPT_WRITEFUNCTION,wr);curl_easy_setopt(curl_,CURLOPT_WRITEDATA,&r.body);curl_easy_setopt(curl_,CURLOPT_HTTP_VERSION,CURL_HTTP_VERSION_2TLS);curl_easy_setopt(curl_,CURLOPT_TCP_KEEPALIVE,1L);curl_easy_setopt(curl_,CURLOPT_TCP_NODELAY,1L);curl_easy_setopt(curl_,CURLOPT_CONNECTTIMEOUT_MS,3000L);curl_easy_setopt(curl_,CURLOPT_TIMEOUT_MS,5000L);curl_easy_setopt(curl_,CURLOPT_NOSIGNAL,1L);auto rc=curl_easy_perform(curl_);if(rc!=CURLE_OK){curl_slist_free_all(hs);throw std::runtime_error(std::string("HTTP failed: ")+curl_easy_strerror(rc));}curl_easy_getinfo(curl_,CURLINFO_RESPONSE_CODE,&r.status);curl_easy_getinfo(curl_,CURLINFO_TOTAL_TIME,&r.total_ms);r.total_ms*=1000;curl_slist_free_all(hs);return r;}
static std::string json_get_any(const pt::ptree&p,std::initializer_list<const char*> keys){for(auto k:keys)if(auto x=p.get_optional<std::string>(k))return*x;return{};}
static std::string jesc(const std::string&s){std::ostringstream o;for(char c:s){if(c=='\\'||c=='\"')o<<'\\'<<c;else if(c=='\n')o<<"\\n";else o<<c;}return o.str();}
static std::string form_escape(const std::string&s){CURL*c=curl_easy_init();char*e=curl_easy_escape(c,s.c_str(),static_cast<int>(s.size()));std::string r=e?e:"";if(e)curl_free(e);curl_easy_cleanup(c);return r;}
static std::vector<uint8_t> base32(std::string s){std::vector<uint8_t>o;int buffer=0,bits=0;for(char ch:s){if(ch=='='||std::isspace(static_cast<unsigned char>(ch)))continue;ch=static_cast<char>(std::toupper(static_cast<unsigned char>(ch)));int v=ch>='A'&&ch<='Z'?ch-'A':ch>='2'&&ch<='7'?26+ch-'2':-1;if(v<0)throw std::runtime_error("invalid base32 TOTP secret");buffer=(buffer<<5)|v;bits+=5;if(bits>=8){o.push_back(static_cast<uint8_t>((buffer>>(bits-8))&0xff));bits-=8;}}return o;}
std::string KotakRestClient::generate_totp(std::string secret,int64_t sec){if(sec==0)sec=static_cast<int64_t>(std::time(nullptr));auto key=base32(std::move(secret));uint64_t counter=static_cast<uint64_t>(sec/30);std::array<unsigned char,8>msg{};for(int i=7;i>=0;--i){msg[static_cast<size_t>(i)]=static_cast<unsigned char>(counter&0xff);counter>>=8;}unsigned int len=0;unsigned char digest[EVP_MAX_MD_SIZE];HMAC(EVP_sha1(),key.data(),static_cast<int>(key.size()),msg.data(),msg.size(),digest,&len);int off=digest[len-1]&0x0f;uint32_t bin=(static_cast<uint32_t>(digest[off]&0x7f)<<24)|(static_cast<uint32_t>(digest[off+1])<<16)|(static_cast<uint32_t>(digest[off+2])<<8)|digest[off+3];uint32_t code=bin%1'000'000;std::ostringstream os;os<<std::setw(6)<<std::setfill('0')<<code;return os.str();}
KotakSession KotakRestClient::login(){KotakSession s;s.consumer_key=env_or(cfg_.consumer_key_env);const auto mobile=env_or(cfg_.mobile_env),ucc=env_or(cfg_.ucc_env),secret=env_or(cfg_.totp_secret_env),totp=secret.empty()?env_or(cfg_.totp_env):generate_totp(secret);const auto mpin=env_or(cfg_.mpin_env);if(s.consumer_key.empty()||mobile.empty()||ucc.empty()||totp.empty()||mpin.empty())throw std::runtime_error("Kotak credentials missing from environment");std::vector<std::string>h={"Authorization: "+s.consumer_key,"neo-fin-key: neotradeapi"};std::string body="{\"mobileNumber\":\""+jesc(mobile)+"\",\"ucc\":\""+jesc(ucc)+"\",\"totp\":\""+jesc(totp)+"\"}";auto r=http_.post(cfg_.login_url,h,body,"application/json");if(r.status/100!=2)throw std::runtime_error("Kotak TOTP login HTTP "+std::to_string(r.status)+": "+r.body.substr(0,200));std::istringstream is(r.body);pt::ptree p;pt::read_json(is,p);s.view_token=json_get_any(p,{"data.token","token"});s.view_sid=json_get_any(p,{"data.sid","sid"});s.ucc=json_get_any(p,{"data.ucc","ucc"});if(s.ucc.empty())s.ucc=ucc;s.data_center=json_get_any(p,{"data.dataCenter","dataCenter"});std::vector<std::string>vh={"Authorization: "+s.consumer_key,"sid: "+s.view_sid,"Auth: "+s.view_token,"neo-fin-key: neotradeapi"};auto vr=http_.post(cfg_.validate_url,vh,"{\"mpin\":\""+jesc(mpin)+"\"}","application/json");if(vr.status/100!=2)throw std::runtime_error("Kotak MPIN validation HTTP "+std::to_string(vr.status)+": "+vr.body.substr(0,200));std::istringstream vis(vr.body);pt::ptree q;pt::read_json(vis,q);s.edit_token=json_get_any(q,{"data.token","token"});s.edit_sid=json_get_any(q,{"data.sid","sid"});s.base_url=json_get_any(q,{"data.baseUrl","baseUrl"});s.feed_url=json_get_any(q,{"data.feedUrl","feedUrl"});auto dc=json_get_any(q,{"data.dataCenter","dataCenter"});if(!dc.empty())s.data_center=dc;if(s.base_url.empty()||s.edit_token.empty()||s.edit_sid.empty())throw std::runtime_error("Kotak validation response missing session/baseUrl");s.valid=true;return s;}
std::vector<std::string>KotakRestClient::order_headers(const KotakSession&s)const{return {"Authorization: "+s.consumer_key,"Sid: "+s.edit_sid,"Auth: "+s.edit_token};}
static std::string side_text(Side s){return s==Side::Buy?"B":"S";}
std::string KotakRestClient::place_order(const KotakSession&s,const OrderIntent&o){std::ostringstream b;b<<"am=NO&dq=0&es="<<form_escape("nse_fo")<<"&mp=0&pc="<<form_escape(o.product)<<"&pr="<<o.price<<"&pt=L&qt="<<o.quantity<<"&rt="<<form_escape(o.validity)<<"&tp=0&ts="<<form_escape(o.symbol)<<"&tt="<<side_text(o.side)<<"&ig="<<form_escape(o.tag)<<"&os=NEOTRADEAPI";auto r=http_.post(s.base_url+"/quick/order/rule/ms/place",order_headers(s),b.str(),"application/x-www-form-urlencoded");if(r.status/100!=2)throw std::runtime_error("place order HTTP "+std::to_string(r.status)+": "+r.body.substr(0,240));std::istringstream is(r.body);pt::ptree p;pt::read_json(is,p);auto id=json_get_any(p,{"data.orderId","data.nOrdNo","orderId","nOrdNo"});if(id.empty())throw std::runtime_error("place order response missing order id: "+r.body.substr(0,240));return id;}
std::string KotakRestClient::modify_order(const KotakSession&s,const OrderIntent&o){if(o.existing_order_id.empty())throw std::runtime_error("modify missing order id");std::ostringstream b;b<<"mp=0&dq=0&vd="<<form_escape(o.validity)<<"&pr="<<o.price<<"&pt=L&am=NO&tp=0&qt="<<o.quantity<<"&no="<<form_escape(o.existing_order_id)<<"&os=NEOTRADEAPI";auto r=http_.post(s.base_url+"/quick/order/vr/modify",order_headers(s),b.str(),"application/x-www-form-urlencoded");if(r.status/100!=2)throw std::runtime_error("modify order HTTP "+std::to_string(r.status)+": "+r.body.substr(0,240));return o.existing_order_id;}
void KotakRestClient::cancel_order(const KotakSession&s,const OrderIntent&o){if(o.existing_order_id.empty())return;auto r=http_.post(s.base_url+"/quick/order/cancel",order_headers(s),"on="+form_escape(o.existing_order_id)+"&am=NO","application/x-www-form-urlencoded");if(r.status/100!=2)throw std::runtime_error("cancel order HTTP "+std::to_string(r.status)+": "+r.body.substr(0,240));}
} // namespace alosmm
