#include "alosmm/policy.hpp"
namespace alosmm {
double StatutoryCostModel::buy_points(double p,int qty)const{const double tx=ex_*p,se=sebi_*p,sd=stamp_*p,br=qty>0?brokerage_/static_cast<double>(qty):0.0;return tx+se+sd+gst_*(tx+se+br)+br;}
double StatutoryCostModel::sell_points(double p,int qty)const{const double tx=ex_*p,se=sebi_*p,br=qty>0?brokerage_/static_cast<double>(qty):0.0;return tx+se+stt_*p+gst_*(tx+se+br)+br;}
const InventoryPosition& InventoryBook::zero_position(){static const InventoryPosition z{};return z;}
const InventoryPosition& InventoryBook::get(const Instrument& inst)const{auto it=pos_.find(inst.token);return it==pos_.end()?zero_position():it->second;}
int InventoryBook::lots(CP cp)const{int out=0;for(const auto& [tok,p]:pos_){auto it=cp_by_token_.find(tok);if(it!=cp_by_token_.end()&&it->second==cp)out+=p.lots;}return out;}
void InventoryBook::on_fill(const Instrument& inst,Side side,double price,int lots_n,double all_in){if(lots_n<=0)throw std::runtime_error("invalid fill lots");auto&p=pos_[inst.token];cp_by_token_[inst.token]=inst.cp;if(side==Side::Buy){if(p.lots+lots_n>cap_)throw std::runtime_error("BUY BLOCKED: inventory cap");p.avg_all_in_price=(p.avg_all_in_price*p.lots+all_in*lots_n)/static_cast<double>(p.lots+lots_n);p.lots+=lots_n;}else{if(p.lots<lots_n)throw std::runtime_error("SELL BLOCKED: negative option inventory forbidden");p.lots-=lots_n;if(p.lots==0){p.avg_all_in_price=0;pos_.erase(inst.token);cp_by_token_.erase(inst.token);}}(void)price;}
double InventoryBook::delta(const std::array<Greeks,2>&g)const{return lots(CP::Call)*g[0].delta+lots(CP::Put)*g[1].delta;}
double InventoryBook::vega(const std::array<Greeks,2>&g)const{return lots(CP::Call)*g[0].vega+lots(CP::Put)*g[1].vega;}
double InventoryBook::gamma(const std::array<Greeks,2>&g)const{return lots(CP::Call)*g[0].gamma+lots(CP::Put)*g[1].gamma;}
AdaptivePolicy::AdaptivePolicy(const Config&c,ModelBank&m):cfg_(c),models_(m),costs_(c),inventory_(c.max_lots_per_contract){}
bool AdaptivePolicy::eligible(const FeatureState&s,std::string&w)const{if(s.best_bid<=0||s.best_ask<=s.best_bid){w="bad book";return false;}if(s.quote_age_s>cfg_.max_quote_age_s){w="option quote stale";return false;}if(s.future_age_s>cfg_.max_future_age_s){w="future stale";return false;}if(cfg_.require_surface){if(s.surface_pairs<cfg_.min_surface_pairs){w="too few surface pairs";return false;}if(s.surface_age_s>cfg_.max_surface_age_s){w="surface stale";return false;}if(s.surface_rmse>cfg_.max_surface_rmse_iv){w="surface fit poor";return false;}if(s.pair_dispersion>cfg_.max_pair_dispersion){w="parity dispersion high";return false;}}w="ok";return true;}
double AdaptivePolicy::inventory_risk_delta(CP cp,Side side,double pfill,const std::array<Greeks,2>&g)const{const double q0=inventory_.total_lots(),d0=inventory_.delta(g),v0=inventory_.vega(g),ga0=inventory_.gamma(g);const double dir=side==Side::Buy?1.0:-1.0,di=g[static_cast<size_t>(cp)].delta*dir,vi=g[static_cast<size_t>(cp)].vega*dir,gai=g[static_cast<size_t>(cp)].gamma*dir,q1=q0+dir;const double change=cfg_.inventory_penalty*(q1*q1-q0*q0)+cfg_.delta_penalty*((d0+di)*(d0+di)-d0*d0)+cfg_.vega_penalty*((v0+vi)*(v0+vi)-v0*v0)+cfg_.gamma_penalty*((ga0+gai)*(ga0+gai)-ga0*ga0);return pfill*change;}
ContractDecision AdaptivePolicy::decide(const FeatureState&s,const Instrument&inst,const std::array<Greeks,2>&pg){ContractDecision d;d.bid.cp=d.ask.cp=inst.cp;d.bid.side=Side::Buy;d.ask.side=Side::Sell;d.bid.ts_ns=d.ask.ts_ns=s.ts_ns;std::string why;if(!eligible(s,why)){d.reason=why;return d;}d.eligible=true;d.reason="ok";d.reservation_value=s.fair_value+s.micro_shift+0.20*s.greeks.delta*(s.futures_ofi_z+s.synthetic_gap_z)*s.spread;
    auto choose=[&](Side side)->QuoteAction{QuoteAction best;best.cp=inst.cp;best.side=side;best.ts_ns=s.ts_ns;best.reason="off";double bestscore=-1e100;for(double off:cfg_.offsets){auto p=models_.predict(inst.cp,side,off,s);if(p.pfill<cfg_.min_fill_probability)continue;double score=p.calibrated_ev-inventory_risk_delta(inst.cp,side,p.pfill,pg)-cfg_.churn_penalty-cfg_.uncertainty_penalty*p.uncertainty;if(score>bestscore){bestscore=score;best.offset=off;best.predicted_fill=p.pfill;best.predicted_conditional_markout=p.conditional;best.predicted_ev=score;}}
        if(bestscore<=-1e90)return best;const double min_ev=side==Side::Buy?cfg_.min_buy_ev:cfg_.min_sell_ev;if(bestscore<min_ev){best.reason="ev_below_threshold";return best;}if(models_.side_observations(inst.cp,side)>100&&models_.side_rolling_ev(inst.cp,side)<cfg_.side_kill_threshold){best.reason="side_kill";return best;}if(side==Side::Buy&&!inventory_.can_buy(inst)){best.reason="inventory_cap";return best;}if(side==Side::Sell&&!inventory_.can_sell(inst)){best.reason="no_inventory";return best;}if(side==Side::Buy){best.price=std::min(s.best_bid,floor_tick(d.reservation_value-best.offset,inst.tick_size));}else{double floor_basis=inventory_.avg_all_in(inst);if(!cfg_.allow_hold_loss&&floor_basis>0)floor_basis+=costs_.sell_points(floor_basis,inst.lot_size);best.price=std::max({s.best_ask,ceil_tick(d.reservation_value+best.offset,inst.tick_size),ceil_tick(floor_basis,inst.tick_size)});}best.enabled=best.price>0;best.reason="selected";return best;};
    d.bid=choose(Side::Buy);d.ask=choose(Side::Sell);return d;}
void AdaptivePolicy::on_fill(const Instrument&i,Side side,double price,int qty){if(qty<=0||qty%i.lot_size!=0)throw std::runtime_error("fill qty not a whole lot");int lots_n=qty/i.lot_size;double allin=price+(side==Side::Buy?costs_.buy_points(price,qty):0);inventory_.on_fill(i,side,price,lots_n,allin);}
bool AdaptivePolicy::should_replace(const Instrument& inst,const ContractDecision&d){auto&old=last_quotes_[static_cast<size_t>(inst.cp)];std::optional<double>b=d.bid.enabled?std::optional<double>(d.bid.price):std::nullopt,a=d.ask.enabled?std::optional<double>(d.ask.price):std::nullopt;auto moved=[&](auto x,auto y){if(x.has_value()!=y.has_value())return true;if(!x)return false;return std::abs(*x-*y)+1e-12>=cfg_.update_threshold_points;};bool r=old.token!=inst.token||moved(old.bid,b)||moved(old.ask,a);if(r){old.token=inst.token;old.bid=b;old.ask=a;}return r;}
} // namespace alosmm
