foreach(required IN ITEMS CMakeLists.txt include src contracts ledger ops tests docs)
  if(NOT EXISTS "${SOURCE_DIR}/${required}")
    message(FATAL_ERROR "missing independent Execution lane: ${required}")
  endif()
endforeach()
file(GLOB_RECURSE cmake_files "${SOURCE_DIR}/CMakeLists.txt" "${SOURCE_DIR}/cmake/*.cmake")
set(project_file "")
foreach(cmake_file IN LISTS cmake_files)
  file(READ "${cmake_file}" cmake_text)
  string(APPEND project_file "\n${cmake_text}")
endforeach()
foreach(forbidden IN ITEMS FetchContent curl OpenSSL AWS ssh)
  if(project_file MATCHES "${forbidden}")
    message(FATAL_ERROR "default target graph references network-capable dependency: ${forbidden}")
  endif()
endforeach()
file(GLOB_RECURSE link_files "${BINARY_ROOT}/../CMakeFiles/*/link.txt")
foreach(link_file IN LISTS link_files)
  file(READ "${link_file}" link_text)
  if(link_text MATCHES "(^|[ /_-])(curl|ssl|crypto|ssh|aws)([ ._/-]|$)")
    message(FATAL_ERROR "default link graph contains network-capable dependency: ${link_file}")
  endif()
endforeach()
